# Generated by Django 3.0.1 on 2019-12-22 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 22, 21, 12, 17, 977724, tzinfo=utc)),
        ),
    ]
