# Generated by Django 2.1.3 on 2020-04-26 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200426_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='premiere',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 26, 18, 1, 46, 216420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='favoritecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
    ]
