# Generated by Django 3.0.6 on 2020-05-26 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200523_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 26, 5, 0, 50, 64875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
    ]
